# Generated by Django 4.2.5 on 2024-01-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_delete_mailinglistgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this Mailing List. e.g. Magic, Wargaming, 2023 Freshers, etc.', max_length=20)),
                ('description', models.CharField(help_text='A brief description of the mailing list. e.g. News about Major Unigames events.', max_length=200)),
                ('verbose_description', models.CharField(help_text="This text will appear as a prompt on the Membership forms. e.g. 'I want to receive news about MtG events.'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='This controls whether people are able to subscribe to this group.')),
                ('members', models.ManyToManyField(related_name='mailing_lists', to='members.member')),
            ],
        ),
    ]
