# Generated by Django 4.2.9 on 2024-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this Blog Post.', max_length=200)),
                ('slug_title', models.SlugField(help_text="An automatically generated, URL-safe title. Generally you don't edit these once the post is created.", max_length=200, unique=True)),
                ('author', models.CharField(help_text="The author of the post. (e.g. 'Donald Sutherland', or 'Unigames Committee')", max_length=200)),
                ('publish_on', models.DateTimeField(blank=True, default=None, help_text='The date and time at which the post will become published. If this is set to a future date, the post will be hidden until then. If left blank, this will never be published (basically saved as a draft.)', null=True)),
                ('body', models.TextField(blank=True, help_text='The body of the post. Markdown enabled.')),
            ],
        ),
    ]
