# Generated by Django 4.2.9 on 2024-06-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(default='', help_text='A short summary of the post to serve as the preview of the contents. Displayed on the ListView and in Emails. Markdown not enabled.', max_length=300),
        ),
    ]
