# Generated by Django 5.1.1 on 2024-10-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_orders', to='blog.blogpost')),
                ('mailing_lists', models.ManyToManyField(related_name='email_orders', to='blog.mailinglist')),
            ],
        ),
    ]
