# Generated by Django 4.2.5 on 2023-12-21 05:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=200)),
                ('pronouns', models.CharField(max_length=50)),
                ('student_number', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('join_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('optional_emails', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.TextField(choices=[('EXCLUDED', 'Excluded'), ('GATEKEEPER', 'Gatekeeper'), ('WEBKEEPER', 'Webkeeper'), ('COMMITTEE', 'Committee'), ('LIFEMEMBER', 'Life Member'), ('PRESIDENT', 'President'), ('VICEPRESIDENT', 'Vice-President'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('LIBRARIAN', 'Librarian'), ('FRESHERREP', 'Fresher-Rep'), ('OCM', 'OCM'), ('IPP', 'IPP (Immediate Past President)')], max_length=20)),
                ('assigned_date', models.DateField(default=datetime.date.today)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='members.member')),
            ],
        ),
    ]
