# Generated by Django 4.2.5 on 2023-12-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='phone_number',
        ),
    ]
