# Generated by Django 4.2.5 on 2024-01-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_membership_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this Mailing List Group. e.g. Magic, Wargaming, 2023 Freshers, etc.', max_length=20)),
                ('description', models.CharField(help_text="This text will appear on the Membership forms. e.g. 'I want to receive news about MtG events.'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='This controls whether people are able to subscribe to this group.')),
                ('members', models.ManyToManyField(related_name='mailing_list_groups', to='members.member')),
            ],
        ),
    ]
