# Generated by Django 4.2.5 on 2024-01-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_mailinglistgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingListGroup',
        ),
    ]
