# Generated by Django 4.2.9 on 2024-02-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_membership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['long_name']},
        ),
    ]
