# Generated by Django 5.1.1 on 2025-01-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(blank=True, help_text='A brief description of the purchase.', max_length=200)),
                ('reference_code', models.CharField(help_text='A unique identifier for this payment.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount transferred.', max_digits=5)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Date and time payment was made.')),
                ('resolved', models.BooleanField(help_text='Check this when the transaction has been resolved / verified.')),
                ('added_by', models.ForeignKey(blank=True, help_text='The Gatekeeper who facilitated the transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_authorised', to='members.member')),
                ('member', models.ForeignKey(blank=True, help_text='The member who made the purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='members.member')),
            ],
        ),
    ]
